### ISSUE TITLE
What should be the content of this path?

### ISSUE THREAD

**Issue by XXLiu-HNU** [ctu-mrs/CTopPRM#4]
![图片](https://github.com/ctu-mrs/CTopPRM/assets/107916318/b2f59725-9bca-4a6d-b99c-6540791d11dd)
When I run the visualization in the example, I get the above error. When I checked in the code, I found this path. What does this mean?
![图片](https://github.com/ctu-mrs/CTopPRM/assets/107916318/5296e909-af1d-44c7-9668-afc34cb5a283)

**Comment by XXLiu-HNU** [comment]
I understand, this path is your working path, but it seems that these files are not in my working path.

**Comment by novosma** [comment]
Hi! The code that is returning the error is trying to create the visualization for each individual step of the algorithm. If this is what you wanted to see, it is required to set PRINT macro in topological_prm_clustering.hpp file to (true) and run the code again. This saves all of the middle steps of the algorithm in the separate files, that are currently missing. Otherwise setting the is_cl variable in columns_2.py resolve the issue and visualize only the final paths as the result.

The path stored in project variable should be just to the directory where you copied the repository, so I assume its '/home/ubuntu/CTopPRM' for you!

**Comment by shangzh0** [comment]
I have met this issue too,but I have no ideas to deal with it.

**Comment by yunrr** [comment]
> I have met this issue too,but I have no ideas to deal with it.

You can try changing the content of the "project" variable on line 184 to your own CTopRPM path (including CTopRPM), and then modify the print(true) macro in the .hpp file. After that, use the command:

./main

**Comment by yunrr** [comment]
> I have met this issue too,but I have no ideas to deal with it.

Maybe you can try changing the content of the "project" variable on line 184 to your own CTopRPM path (including CTopRPM), and then modify the print(true) macro in the .hpp file. After that, use the command:
./main
